# Generated by Django 5.0.4 on 2024-04-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businfo',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
    ]
