# Generated by Django 5.0.4 on 2024-04-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorickshawInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=255)),
                ('is_running', models.BooleanField(default=False)),
                ('contact_number', models.CharField(max_length=20)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=19)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=19)),
                ('pending_bookings_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
