# Generated by Django 5.0.4 on 2024-04-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_autorickshawinfo_delete_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='autorickshawinfo',
            name='vehicle_key',
            field=models.CharField(default='', max_length=15),
        ),
    ]
