# Generated by Django 5.0.4 on 2024-04-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_autorickshawinfo_vehicle_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday_Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city_to_terminal_time', models.TimeField()),
                ('from_terminal_to_city_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Weekend_Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city_to_terminal_time', models.TimeField()),
                ('from_terminal_to_city_time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='autorickshawinfo',
            name='vehicle_key',
            field=models.CharField(max_length=15),
        ),
    ]
