# Generated by Django 5.0.4 on 2024-04-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_weekday_timing_weekend_timing_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weekday_Timing',
        ),
        migrations.DeleteModel(
            name='Weekend_Timing',
        ),
    ]
